#!/bin/bash
set -o errexit -o pipefail

export JAVA_LIBRARY_PATH="/usr/local/lib:/lib:/usr/lib"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-/lib}"
export LD_LIBRARY_PATH="$JAVA_LIBRARY_PATH:$LD_LIBRARY_PATH"

app_jars=( /chronos/target/chronos*.jar )
main=com.airbnb.scheduler.Main

heap=2048m
environment_directory=/chronos/environment
ip=$(ifconfig | grep inet | grep -v inet6 | grep -v '127.0.0.1' | awk -F: '{ print $2 }' | awk '{ print $1 }')

# Setup the libprocess ip
mkdir -p $environment_directory
echo "$ip" > "$environment_directory"/LIBPROCESS_IP

echo "Using ${app_jars[0]}"

jvm_options=( -cp "${app_jars[0]}" -server -Xmx"$heap" -Xms"$heap"
              -XX:+PrintClassHistogram
              )

if [ -z "$EXHIBITOR_HOST" ]
then
  echo "EXHIBITOR_HOST not set, using localhost:2181"
  zookeepers=localhost:2181
else
  zookeepers=$(/usr/local/bin/zookeepers.rb $EXHIBITOR_HOST)
fi

app_options=( --hostname `hostname` --http_port 8081 --master zk://${zookeepers}/mesos --zk_hosts zk://${zookeepers}/mesos )

function start {
  echo "$(date): $(env)"
  echo "$(date) [ulimit] $(ulimit -n)"
  exec chpst -u www-data -e $environment_directory  java "${jvm_options[@]}" "$main" "${app_options[@]}" 2>&1
}

start
